### PR TITLE
Bump to 7.3.495.0

### PR DESCRIPTION
**Pull request by runlevel5**
## Changes

* I have requested TravisCI to extend timeout from 50m to 120m
* Bump to 7.3.495.0
* Drop testing against Ruby 2.4 (EOL) and rbx (precompiled version is old)
* Test against Ruby 2.6 and 2.7
* Drop testing with XCode 9.2 (the upstream tooling yield dylib error) - the objective now is to get a green build to unblock development - we could revisit this in a separate PR

### CODE REVIEW

**Comment by runlevel5** [comment]
@ignisf @SamSaffron it is now :green_circle: , let's get this project back on track

**Comment by SamSaffron** [comment]
Fantastic, @ignisf  we good to merge? 

I think v8 is up to 8.1 now, can we try this?

**Comment by runlevel5** [comment]
@SamSaffron let's try to bump to 8 after this PR.

**Comment by runlevel5** [comment]
@SamSaffron any update on this PR review? TIA

**Comment by SamSaffron** [comment]
I am guessing @ignisf  is out at the moment, his profile says busy. 

I am going to merge this now. Maybe give a shot at upgrading v8 to 8.1 next, would love to get MiniRacer on latest.

**Pull request merged**
