### PR TITLE
Bump version from 7.3 to 8.1

### PR DESCRIPTION
**Pull request by ksylvest**
Also freezing version constant and switching from double to single quotes to match style used in project.

### CODE REVIEW

**Comment by runlevel5** [comment]
LGTM :+1:

**Comment by runlevel5** [comment]
@ksylvest Would you be able to verify if this new version works fine with https://github.com/rubyjs/mini_racer?

**Comment by ksylvest** [comment]
@runlevel5 Thanks for the response / review. I ran into some issues during that verification:

https://github.com/rubyjs/libv8/issues/298

Did you want me to hold off on the merge until that is fixed?

**Comment by runlevel5** [comment]
@ksylvest I would hold off any version bump till mini_racer catches up.

The recent bump to latest 7.3 still causes [issue with mini_racer](https://meta.discourse.org/t/mini-racer-breaks-build-on-latest-release/116028)

**Comment by nightpool** [comment]
Thanks for your contribution! After many months and many contributors, we finally managed to upgrade to V8 8.4 here: #301, with the corresponding mini_racer PR here: https://github.com/rubyjs/mini_racer/pull/166

Thanks again!

**Pull request closed without merging**
